import type { ThemeContribution } from '../tokens';

export const defaultDark: ThemeContribution = {
  id: 'default-dark',
  label: 'Default Dark',
  uiKind: 'dark',
  tokens: {
    'color.background.workbench': '#1e1e2e',
    'color.background.titlebar':  '#181825',
    'color.background.banner':    '#313244',
    'color.background.sidebar':   '#181825',
    'color.background.editor':    '#1e1e2e',
    'color.background.panel':     '#181825',
    'color.background.statusbar': '#181825',
    'color.foreground.primary':   '#cdd6f4',
    'color.foreground.secondary': '#a6adc8',
    'color.foreground.muted':     '#6c7086',
    'color.border.default':       '#313244',
    'color.border.focus':         '#89b4fa',
    'color.accent.default':       '#89b4fa',
    'color.accent.hover':         '#b4d0fb',
    'color.accent.pressed':       '#74a8f9',
    'color.semantic.info':        '#89dceb',
    'color.semantic.warning':     '#f9e2af',
    'color.semantic.error':       '#f38ba8',
    'color.semantic.success':     '#a6e3a1',
    'space.1': '4px',
    'space.2': '8px',
    'space.3': '12px',
    'space.4': '16px',
    'space.6': '24px',
    'space.8': '32px',
    'radius.sm': '4px',
    'radius.md': '8px',
    'font.sans': "system-ui, 'Segoe UI', Roboto, sans-serif",
    'font.mono': "ui-monospace, Consolas, monospace",
  },
};
