import type { ThemeContribution } from '../tokens';

export const defaultLight: ThemeContribution = {
  id: 'default-light',
  label: 'Default Light',
  uiKind: 'light',
  tokens: {
    'color.background.workbench': '#eff1f5',
    'color.background.titlebar':  '#dce0e8',
    'color.background.banner':    '#ccd0da',
    'color.background.sidebar':   '#e6e9ef',
    'color.background.editor':    '#eff1f5',
    'color.background.panel':     '#e6e9ef',
    'color.background.statusbar': '#dce0e8',
    'color.foreground.primary':   '#4c4f69',
    'color.foreground.secondary': '#5c5f77',
    'color.foreground.muted':     '#9ca0b0',
    'color.border.default':       '#ccd0da',
    'color.border.focus':         '#1e66f5',
    'color.accent.default':       '#1e66f5',
    'color.accent.hover':         '#2b75f8',
    'color.accent.pressed':       '#1558e0',
    'color.semantic.info':        '#04a5e5',
    'color.semantic.warning':     '#df8e1d',
    'color.semantic.error':       '#d20f39',
    'color.semantic.success':     '#40a02b',
    'space.1': '4px',
    'space.2': '8px',
    'space.3': '12px',
    'space.4': '16px',
    'space.6': '24px',
    'space.8': '32px',
    'radius.sm': '4px',
    'radius.md': '8px',
    'font.sans': "system-ui, 'Segoe UI', Roboto, sans-serif",
    'font.mono': "ui-monospace, Consolas, monospace",
  },
};
